# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.blacklistedKernelModules = [ "snd_hda_intel" "snd_soc_skl" ];
  boot.kernelModules =
    [ "acpi_call" "kvm_intel" "yoga-usage-mode" "cpuid" "i2c-dev" "coretemp" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    acpi_call
    (callPackage ./yoga-usage-mode.nix { })
  ];
  boot.kernelPatches = [
    {
      name = "thunderbolt-fix";
      patch = builtins.fetchurl
        "https://bugzilla.kernel.org/attachment.cgi?id=287661";
    }
    {
      name = "zen-config";
      patch = null;
      extraConfig = ''
        # placeholder
      '';
    }
  ];
  boot.extraModprobeConfig = "options zfs zfs_arc_max=1073741824";

  fileSystems."/" = {
    device = "ZFSROOT/root/nixos";
    fsType = "zfs";
  };

  fileSystems."/nix" = {
    device = "ZFSROOT/local/nix";
    fsType = "zfs";
  };

  fileSystems."/home" = {
    device = "ZFSROOT/home";
    fsType = "zfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/734C-3B5D";
    fsType = "vfat";
  };

  fileSystems."/var/lib/docker" = {
    device = "/dev/disk/by-uuid/96525a2d-d14f-4952-a7bb-c436c98b7afb";
    fsType = "ext4";
    # options = ["noauto" "x-systemd.automount"];
    noCheck = true;
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/a16ee42a-6e86-4462-9629-cd757044fed1"; }];

  networking.hostName = "walnut"; # Define your hostname.
  networking.hostId = "6d1612eb";
  networking.interfaces.wlp0s20f3.useDHCP = true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  services.hardware.bolt.enable = true;

  virtualisation = { kvmgt.enable = true; };
  virtualisation.kvmgt.vgpus = {
    "i915-GVTg_V5_8" = { uuid = [ "a297db4a-f4c2-11e6-90f6-d3b88d6c9525" ]; };
  };

  services.tlp = {
    settings = { "USB_BLACKLIST" = [ "046d:c53a" "feed:1307" ]; };
  };

  services.throttled = {
    enable = true;
    extraConfig = ''
      [GENERAL]
      # Enable or disable the script execution
      Enabled: True
      # SYSFS path for checking if the system is running on AC power
      Sysfs_Power_Path: /sys/class/power_supply/ADP1/online
      # Auto reload config on changes
      Autoreload: True

      [BATTERY]
      Update_Rate_s: 30
      # Max package power for time window #1
      PL1_Tdp_W: 25
      # Time window #1 duration
      PL1_Duration_s: 14
      # Max package power for time window #2
      PL2_Tdp_W: 45
      # Time window #2 duration
      PL2_Duration_S: 0.002
      # Max allowed temperature before throttling
      Trip_Temp_C: 85
      # Set cTDP to normal=0, down=1 or up=2 (EXPERIMENTAL)
      cTDP: 1
      # Disable BDPROCHOT (EXPERIMENTAL)
      Disable_BDPROCHOT: True

      [AC]
      Update_Rate_s: 5
      # Max package power for time window #1
      PL1_Tdp_W: 25
      # Time window #1 duration
      PL1_Duration_s: 14
      # Max package power for time window #2
      PL2_Tdp_W: 45
      # Time window #2 duration
      PL2_Duration_S: 0.002
      # Max allowed temperature before throttling
      Trip_Temp_C: 85
      # Set HWP energy performance hints to 'performance' on high load (EXPERIMENTAL)
      HWP_Mode: True
      # Set cTDP to normal=0, down=1 or up=2 (EXPERIMENTAL)
      cTDP: 2
      # Disable BDPROCHOT (EXPERIMENTAL)
      Disable_BDPROCHOT: True

      [UNDERVOLT]
      # CPU core voltage offset (mV)
      CORE: -50
      # Integrated GPU voltage offset (mV)
      GPU: -50
      # CPU cache voltage offset (mV)
      CACHE: -50
      # System Agent voltage offset (mV)
      UNCORE: -50
      # Analog I/O voltage offset (mV)
      ANALOGIO: 0
    '';
  };
}
