#!/usr/bin/env bash

HM_EXEC=~/.nix-profile/bin/nh
CONFIG_FLAKE_PATH=~/src/github.com/cassandracomar/nix-config

echo "invoking home-manager"

case $1 in
    test)
        exec $HM_EXEC home switch --override-input nix-config "path:$CONFIG_FLAKE_PATH" "$@" ~/.config/home-manager
        ;;
    upgrade)
        git -C $CONFIG_FLAKE_PATH pull
        shift
        case $1 in
            --all)
                shift
                echo "updating all flake inputs: $CONFIG_FLAKE_PATH"
                nix flake update --flake $CONFIG_FLAKE_PATH --commit-lock-file
                ;;
            *)
                echo "updating flake inputs: $CONFIG_FLAKE_PATH/nixpkgs"
                nix flake update --flake $CONFIG_FLAKE_PATH nixpkgs --commit-lock-file
                ;;
        esac

        git -C $CONFIG_FLAKE_PATH push
        exec $HM_EXEC home switch -u "$@" ~/.config/home-manager
        ;;
    *)
        exec $HM_EXEC home "$@" -u ~/.config/home-manager
        ;;
esac
