#!/usr/bin/env bash

HM_EXEC=~/.nix-profile/bin/home-manager
HM_ARGS=("--log-format" "internal-json" "-v")
NOM_EXEC=~/.nix-profile/bin/nom
CONFIG_FLAKE_PATH=~/src/github.com/cassandracomar/nix-config

echo "invoking home-manager"

case $1 in
    test)
        nix flake update --flake ~/.config/home-manager --override-input nix-config "path:$CONFIG_FLAKE_PATH"
        $HM_EXEC --override-input nix-config "path:$CONFIG_FLAKE_PATH" "${HM_ARGS[@]}" "$@" |& $NOM_EXEC --json
        ;;
    upgrade)
        git -C $CONFIG_FLAKE_PATH pull
        shift
        case $1 in
            --all)
                shift
                echo "updating all flake inputs: $CONFIG_FLAKE_PATH"
                nix flake update --flake $CONFIG_FLAKE_PATH --commit-lock-file
                ;;
            *)
                echo "updating flake inputs: $CONFIG_FLAKE_PATH/nixpkgs"
                nix flake update --flake $CONFIG_FLAKE_PATH nixpkgs --commit-lock-file
                ;;
        esac

        git -C $CONFIG_FLAKE_PATH push
        nix flake update --flake ~/.config/home-manager 
        $HM_EXEC switch "${HM_ARGS[@]}" "$@" |& $NOM_EXEC --json
        ;;
    *)
        nix flake update --flake ~/.config/home-manager 
        $HM_EXEC "${HM_ARGS[@]}" "$@" |& $NOM_EXEC --json
        ;;
esac
