#!/usr/bin/env bash

before=$(realpath "$(which emacs)")
NR_EXEC=/run/current-system/sw/bin/nixos-rebuild
NR_ARGS=("--log-format" "internal-json" "-v")
NOM_EXEC=/run/current-system/sw/bin/nom
CONFIG_FLAKE_PATH=~/src/github.com/cassandracomar/nix-config

emacs_checked_update() {
    before=$(realpath "$(which emacs)")
    $*
}

echo "invoking nixos-rebuild"

case $1 in
    test)
        sudo nix flake update --flake /etc/nixos --override-input nix-config "path:$CONFIG_FLAKE_PATH"
        emacs_checked_update sudo $NR_EXEC --impure --override-input nix-config "path:$CONFIG_FLAKE_PATH" "${NR_ARGS[@]}" $* | $NOM_EXEC --json
        ;;
    upgrade)
        shift
        case $1 in
            --all)
                shift
                echo "updating all flake inputs: $CONFIG_FLAKE_PATH"
                nix flake update --flake $CONFIG_FLAKE_PATH --commit-lock-file
                ;;
            *)
                echo "updating flake inputs: $CONFIG_FLAKE_PATH/nixpkgs"
                nix flake update --flake $CONFIG_FLAKE_PATH nixpkgs --commit-lock-file
                ;;
        esac

        cd $CONFIG_FLAKE_PATH
        git push
        sudo nix flake update --flake /etc/nixos
        emacs_checked_update sudo $NR_EXEC switch --impure "${NR_ARGS[@]}" $* | $NOM_EXEC --json
        ;;
    *)
        sudo nix flake update --flake /etc/nixos
        emacs_checked_update sudo $NR_EXEC --impure "${NR_ARGS[@]}" $* | $NOM_EXEC --json
        ;;
esac
