#!/usr/bin/env bash

export TERM=eterm
before=$(realpath "$(which emacs)")
NR_EXEC=/run/current-system/sw/bin/nixos-rebuild
CONFIG_FLAKE_PATH=/home/cassandra/src/github.com/cassandracomar/nix-config

emacs_checked_update() {
    before=$(realpath "$(which emacs)")
    $*

    if [ "$(realpath $(which emacs))" != "$before" ]; then
        echo "emacs changed. invoking native compilation rebuild."
        ~/.emacs.d/bin/doom build
    fi
}

echo "invoking nixos-rebuild"

sudo mkdir -p /data/androidKeys
sudo mount -t tmpfs -o mode=750,uid=1000,gid=30000 tmpfs /data/androidKeys
trap 'rv=$?; sudo umount /data/androidKeys; exit $?' EXIT INT TERM QUIT
sops --pgp "0xF431E5E70CAB3E2E" -d --extract '["data"]' --config ~/.config/sops/.sops.yaml ~/.config/sops/age/android-keystore-private-key.yaml > /data/androidKeys/keys.txt
sops --pgp "0xF431E5E70CAB3E2E" -d --extract '["data"]' --config ~/.config/sops/.sops.yaml ~/.config/sops/age/route53-private-key.yaml >> /data/androidKeys/keys.txt
cat /data/androidKeys/keys.txt

case $1 in
    test)
        sudo nix flake lock /etc/nixos --override-input nix-config "path:$CONFIG_FLAKE_PATH" --override-input nix-config/robotnix "path:/home/cassandra/src/github.com/danielfullmer/robotnix"
        emacs_checked_update sudo $NR_EXEC --impure --override-input nix-config "path:$CONFIG_FLAKE_PATH" --override-input nix-config/robotnix "path:/home/cassandra/src/github.com/danielfullmer/robotnix" $*
        ;;
    upgrade)
        shift
        case $1 in
            --all)
                shift
                echo "updating all flake inputs: $CONFIG_FLAKE_PATH"
                nix flake update $CONFIG_FLAKE_PATH --commit-lock-file
                ;;
            *)
                echo "updating flake inputs: $CONFIG_FLAKE_PATH/nixpkgs"
                nix flake lock $CONFIG_FLAKE_PATH --update-input nixpkgs --commit-lock-file
                ;;
        esac

        cd $CONFIG_FLAKE_PATH
        git push
        sudo nix flake update /etc/nixos
        emacs_checked_update sudo $NR_EXEC switch --impure $*
        ;;
    *)
        sudo nix flake update /etc/nixos
        emacs_checked_update sudo $NR_EXEC --impure $*
        ;;
esac
